### ISSUE TITLE
Spring Boot 2.6 Migration

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-spring#170]
Migration recipe for [Spring-Boot-2.6](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes)

This task is to review and identify tasks required for migrating an app from Spring-Boot 2.5 to 2.6

- [x] #177
- [ ] Deprecations from 2.4 are removed ensure they are all accounted for in the 2.4 and 2.5 conversions
- [ ] PathPattern Based Path Matching Strategy for Spring MVC
- [ ] Actuator Env InfoContributor Disabled by Default
- [ ] Application Startup -> `spring.boot.application.running` renamed to `spring.boot.application.ready`
- [x] #178
- [ ] #179
- [x] #184
- [ ] Embedded Mongo
- [ ] Oracle Database Driver Dependency Management
- [ ] Vault-related Flyay Properties Removed
- [ ] WebFlux Session Properties
- [ ] Elasticsearch Property Consolidation
- [ ] #180
- [ ] Maven Build Info’s Default Time
- [ ] Records and `@ConfigurationProperties`
- [ ] Deferred OpenID Connect Discovery
- [x] #181
- [ ] #182

**Comment by timtebeek** [comment]
Some further required changes:
- [ ] Upgrade Spring Cloud release train from 2020.0.x to 2021.0.x (presently: 2021.0.1) as per [release train spring boot compatibility](https://spring.io/projects/spring-cloud)
- [ ] Spring Data Elasticsearch has [some breaking changes](https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch-migration-guide-4.2-4.3.breaking-changes), especially around SearchHits with aggregations

**Comment by pway99** [comment]
Thanks @timtebeek  added these to the main list :)

**Comment by timtebeek** [comment]
Closing this issue as we've covered the well-trodden paths for folks already; anything left can be contributed separated as needed.
