### ISSUE TITLE
Recipes to upgrade to Spring Framework 6.2

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-spring#627]
We want to support migrations to Spring Framework 6.2, as part of a migration to Spring Boot 3.4.

Here's a quick link to the release notes: https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-6.2-Release-Notes

And here's an incomplete list of necessary steps for this migration:
- [x] Deprecated APIs removed in https://github.com/spring-projects/spring-framework/issues/30608
  - https://github.com/openrewrite/rewrite-spring/pull/693
  - https://github.com/openrewrite/rewrite-spring/pull/689
- [x] Additional APIs removed in https://github.com/spring-projects/spring-framework/issues/33123
- [ ] WebContentGenerator removed in https://github.com/spring-projects/spring-framework/issues/31492
- [ ] Migrating from HtmlUnit 2.x.x to HtmlUnit 3.x.x as per https://htmlunit.sourceforge.io/migration.html
  - [ ] ~https://github.com/openrewrite/rewrite-testing-frameworks/pull/643~
  - [ ] Include the HtmlUnit migrations with the Spring Framework 6.2 upgrade: https://docs.openrewrite.org/recipes/java/testing/htmlunit/upgradehtmlunit_3

We welcome anyone to pick off individual items here in pull requests, even if it's just a draft PR with unit tests added.

**Comment by timtebeek** [comment]
hi! Those recipes first have to be written and contributed to the project; I've logged a small break down of tasks for Spring Boot:
- https://github.com/openrewrite/rewrite-spring/issues/642

Welcome to help out on either the steps here or on that other issue.

**Comment by timtebeek** [comment]
This PR from @wapkch helpfully includes some of the steps above already:
- https://github.com/openrewrite/rewrite-spring/pull/693
